require('dotenv').config({path:'.env.test',override:true});
const request=require('supertest'),argon2=require('argon2'),fs=require('fs'),JSZip=require('jszip');
const {Test}=require('@nestjs/testing');const {ValidationPipe}=require('@nestjs/common');
const {AppModule}=require('../dist/src/app.module');const {PrismaService}=require('../dist/src/database/prisma.service');const {grantAdminPermissions}=require('../dist/src/auth/admin-permissions');
const {resolveGeneratedDir}=require('../dist/src/contracts/documents/contract-document.builder');
const {join}=require('path');
jest.setTimeout(30000);
describe('Contrato oficial persistente',()=>{
 let app,prisma,org,token,client,contract;const auth=()=>({Authorization:`Bearer ${token}`});
 beforeAll(async()=>{
  const module=await Test.createTestingModule({imports:[AppModule]}).compile();app=module.createNestApplication();app.setGlobalPrefix('api');app.useGlobalPipes(new ValidationPipe({whitelist:true,forbidNonWhitelisted:true,transform:true}));await app.init();prisma=app.get(PrismaService);
  expect((await prisma.$queryRawUnsafe('SELECT current_database() AS name'))[0].name).toBe('sistem_auditoria_test');
  org=await prisma.organization.create({data:{name:`TEST_CONTRACT_OFFICIAL_${Date.now()}`}});const role=await prisma.role.create({data:{organizationId:org.id,name:'ADMIN'}});await prisma.$transaction(tx=>grantAdminPermissions(tx,role.id));
  const email=`official-${org.id}@example.test`;await prisma.user.create({data:{organizationId:org.id,email,passwordHash:await argon2.hash('test-contract-only'),firstName:'TEST',lastName:'Admin',roles:{create:{roleId:role.id}}}});
  token=(await request(app.getHttpServer()).post('/api/auth/login').send({email,password:'test-contract-only'}).expect(201)).body.accessToken;
  client=(await request(app.getHttpServer()).post('/api/clients').set(auth()).send({legalName:'TEST TIA S.A.',taxId:'0091234567001',economicActivity:'Servicios profesionales',email:'empresa@example.test',country:'EC',representative:{treatment:'Sra.',fullName:'TEST María Pérez',nationalId:'0123456789',position:'Gerente General'}}).expect(201)).body;
 });
 afterAll(async()=>{if(org){const where={client:{organizationId:org.id}};const docs=await prisma.generatedDocument.findMany({where:{contract:where}});for(const d of docs)if(d.storageKey)fs.rmSync(join(resolveGeneratedDir(),d.storageKey),{force:true});await prisma.generatedDocument.deleteMany({where:{contract:where}});await prisma.auditLog.deleteMany({where:{organizationId:org.id}});await prisma.contract.deleteMany({where});await prisma.auditPeriod.deleteMany({where});await prisma.client.deleteMany({where:{organizationId:org.id}});await prisma.userRole.deleteMany({where:{user:{organizationId:org.id}}});await prisma.user.deleteMany({where:{organizationId:org.id}});await prisma.rolePermission.deleteMany({where:{role:{organizationId:org.id}}});await prisma.role.deleteMany({where:{organizationId:org.id}});await prisma.organization.delete({where:{id:org.id}})}await app?.close()});
 test('exige autenticación y valida año/cliente',async()=>{await request(app.getHttpServer()).post('/api/contracts').send({clientId:client.id,auditedYear:2027}).expect(401);await request(app.getHttpServer()).post('/api/contracts').set(auth()).send({clientId:client.id,auditedYear:0}).expect(400);await request(app.getHttpServer()).post('/api/contracts').set(auth()).send({clientId:'foreign',auditedYear:2027}).expect(404)});
 test('prepara copia con datos seguros sin derivar fechas',async()=>{contract=(await request(app.getHttpServer()).post('/api/contracts').set(auth()).send({clientId:client.id,auditedYear:2027}).expect(201)).body;expect(contract.variables.values.REPRESENTATIVE_TITLE).toBe('Sra.');expect(contract.signingDate).toBeNull();expect(contract.clauses.find(s=>s.clauseKey==='p60').body).toContain('2025');expect(contract.clauses.find(s=>s.clauseKey==='p46').body).toContain('2026');expect(contract.clauses.find(s=>s.clauseKey==='p1').body).toContain('2027');await request(app.getHttpServer()).post('/api/contracts').set(auth()).send({clientId:client.id,auditedYear:2027}).expect(409)});
 test('guarda solo una cláusula y Word usa el contenido persistido',async()=>{
  const first=contract.clauses.find(s=>s.clauseKey==='p45');const second=contract.clauses.find(s=>s.clauseKey==='p46');const untouched=contract.clauses.find(s=>s.clauseKey==='p1');
  const firstBody=first.body.replace('10 días hábiles','20 días hábiles');const secondBody=second.body.replace('2026','2028');
  await request(app.getHttpServer()).patch(`/api/contracts/${contract.id}/clauses/${contract.clauses.find(s=>s.clauseKey==='p10').id}`).set(auth()).send({body:'Texto fijo'}).expect(200);
  await request(app.getHttpServer()).patch(`/api/contracts/${contract.id}/clauses/${first.id}`).set(auth()).send({body:firstBody}).expect(200);
  let reopened=(await request(app.getHttpServer()).get(`/api/contracts/${contract.id}`).set(auth()).expect(200)).body;
  expect(reopened.clauses).toHaveLength(contract.clauses.length);expect(reopened.clauses.find(s=>s.id===first.id).body).toBe(firstBody);expect(reopened.clauses.find(s=>s.id===second.id).body).toBe(second.body);expect(reopened.clauses.find(s=>s.id===untouched.id).body).toBe(untouched.body);
  await request(app.getHttpServer()).patch(`/api/contracts/${contract.id}/clauses/${second.id}`).set(auth()).send({body:secondBody}).expect(200);
  reopened=(await request(app.getHttpServer()).get(`/api/contracts/${contract.id}`).set(auth()).expect(200)).body;
  expect(reopened.clauses).toHaveLength(contract.clauses.length);expect(reopened.clauses.find(s=>s.id===first.id).body).toBe(firstBody);expect(reopened.clauses.find(s=>s.id===second.id).body).toBe(secondBody);expect(reopened.clauses.find(s=>s.id===untouched.id).body).toBe(untouched.body);
  const fifth=reopened.clauses.find(s=>s.clauseKey==='p20'),sixth=reopened.clauses.find(s=>s.clauseKey==='p28');
  const paragraph=(await request(app.getHttpServer()).post(`/api/contracts/${contract.id}/clauses/${fifth.id}/paragraphs`).set(auth()).send({body:'Párrafo agregado únicamente a QUINTA.'}).expect(201)).body;
  const added=(await request(app.getHttpServer()).post(`/api/contracts/${contract.id}/clauses`).set(auth()).send({title:'DÉCIMA CUARTA – DISPOSICIÓN ADICIONAL',body:'Cláusula insertada entre QUINTA y SEXTA.',insertBeforeClauseId:sixth.id}).expect(201)).body;
  reopened=(await request(app.getHttpServer()).get(`/api/contracts/${contract.id}`).set(auth()).expect(200)).body;
  expect(reopened.clauses.find(s=>s.id===paragraph.id).body).toContain('QUINTA');expect(reopened.clauses.findIndex(s=>s.id===added.id)).toBeGreaterThan(reopened.clauses.findIndex(s=>s.id===fifth.id));expect(reopened.clauses.findIndex(s=>s.id===added.id)).toBeLessThan(reopened.clauses.findIndex(s=>s.id===sixth.id));
  const preview=(await request(app.getHttpServer()).get(`/api/contracts/${contract.id}/preview`).set(auth()).expect(200)).body;expect(preview.sections.find(s=>s.id===first.id).body).toBe(firstBody);expect(preview.sections.find(s=>s.id===second.id).body).toBe(secondBody);
  expect(preview.sections.find(s=>s.id===paragraph.id).body).toContain('QUINTA');expect(preview.sections.find(s=>s.id===added.id).body).toContain('Cláusula insertada');
 const doc=(await request(app.getHttpServer()).post(`/api/contracts/${contract.id}/documents`).set(auth()).send({format:'docx'}).expect(201)).body;const record=await prisma.generatedDocument.findUnique({where:{id:doc.id}});const zip=await JSZip.loadAsync(fs.readFileSync(join(resolveGeneratedDir(),record.storageKey)));const content=(await zip.file('word/document.xml').async('string')).replace(/<[^>]+>/g,'');expect(content).toContain('20 días hábiles');expect(content).toContain('2028');expect(content).toContain('2027');expect(content).toContain('Párrafo agregado únicamente a QUINTA.');expect(content).toContain('DÉCIMA CUARTA');expect(doc.originalFileName).toBe('Contrato_TEST_TIA_S_A_2027.docx');
  const cached=(await request(app.getHttpServer()).post(`/api/contracts/${contract.id}/documents`).set(auth()).send({format:'docx'}).expect(201)).body;expect(cached.id).toBe(doc.id);expect(await prisma.generatedDocument.count({where:{contractId:contract.id,type:'CONTRACT_DOCX'}})).toBe(1);
  const updatedBody=`${firstBody} Texto de actualización para invalidar caché.`;
  await request(app.getHttpServer()).patch(`/api/contracts/${contract.id}/clauses/${first.id}`).set(auth()).send({body:updatedBody}).expect(200);
  const regenerated=(await request(app.getHttpServer()).post(`/api/contracts/${contract.id}/documents`).set(auth()).send({format:'docx'}).expect(201)).body;expect(regenerated.id).not.toBe(doc.id);expect(await prisma.generatedDocument.count({where:{contractId:contract.id,type:'CONTRACT_DOCX'}})).toBe(2);
 });
});
