import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { Link } from 'react-router-dom';
import { clientRegistrationSchema, type ClientRegistrationValues } from '../schemas/client.schema';
import type { Client, CreateClientPayload, UpdateClientPayload } from '../services/clients.api';
import { ClientIcon } from './client-icon';

export function ClientForm({client,isPending,serverError,onSubmit}:{client?:Client;isPending:boolean;serverError:string|null;onSubmit:(payload:CreateClientPayload|UpdateClientPayload)=>void}) {
 const rep=client?.representatives?.[0];
 const {register,handleSubmit,formState:{errors}}=useForm<ClientRegistrationValues>({resolver:zodResolver(clientRegistrationSchema),defaultValues:{legalName:client?.legalName??'',taxId:client?.taxId??'',economicActivity:client?.economicActivity??'',email:client?.email??'',treatment:(rep?.treatment==='Sra.'?'Sra.':'Sr.') as 'Sr.'|'Sra.',fullName:rep?.fullName??'',nationalId:rep?.nationalId??'',position:rep?.position??''}});
 const error=(key:keyof ClientRegistrationValues)=>errors[key]&&<span id={`error-${key}`} className="clients-field-error">{errors[key]?.message}</span>;
 const input=(key:keyof ClientRegistrationValues,label:string,required=false,type='text')=><label className="clients-field" key={key} htmlFor={`client-${key}`}>{label}{required?' *':''}<input id={`client-${key}`} type={type} autoComplete={key==='email'?'email':'off'} {...register(key)} aria-required={required} aria-invalid={!!errors[key]} aria-describedby={errors[key]?`error-${key}`:undefined}/> {error(key)}</label>;
 return <form className="clients-form" noValidate onSubmit={handleSubmit(values=>onSubmit({legalName:values.legalName,taxId:values.taxId,economicActivity:values.economicActivity,email:values.email,...(!client?{country:'EC'}:{}),representative:{...(rep?{id:rep.id}:{}),treatment:values.treatment,fullName:values.fullName,nationalId:values.nationalId,position:values.position}}))}>
 {serverError&&<p role="alert" className="clients-error">{serverError}</p>}<fieldset disabled={isPending}><div className="clients-columns"><section className="clients-card" aria-label="Datos de la empresa"><h2><ClientIcon name="building"/>Datos de la empresa</h2>{input('legalName','Razón social',true)}{input('taxId','RUC',true)}<label className="clients-field" htmlFor="client-economicActivity">Actividad económica principal *<textarea id="client-economicActivity" {...register('economicActivity')} rows={4} aria-required aria-invalid={!!errors.economicActivity} aria-describedby={errors.economicActivity?'error-economicActivity':undefined}/> {error('economicActivity')}</label>{input('email','Correo electrónico de la empresa',true,'email')}</section><section className="clients-card" aria-label="Representante legal"><h2><ClientIcon name="user"/>Representante legal</h2><label className="clients-field" htmlFor="client-treatment">Tratamiento *<select id="client-treatment" {...register('treatment')} aria-required aria-invalid={!!errors.treatment} aria-describedby={errors.treatment?'error-treatment':undefined}><option value="Sr.">Sr.</option><option value="Sra.">Sra.</option></select> {error('treatment')}</label>{input('fullName','Nombre completo',true)}{input('nationalId','Cédula',true)}{input('position','Cargo',true)}</section></div></fieldset><div className="clients-form-actions"><Link className="clients-button clients-button-outline" to={client?`/clientes/${client.id}`:'/clientes'}>Cancelar</Link><button type="submit" className="clients-button clients-button-brown" disabled={isPending}><ClientIcon name="save"/>{isPending?'Guardando...':client?'Guardar cambios':'Guardar cliente'}</button></div></form>;
}
