import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { AuthProvider } from './auth-context'; import { useAuth } from './use-auth'; import { session } from '../services/session';
const { login, me, post }=vi.hoisted(()=>({login:vi.fn(),me:vi.fn(),post:vi.fn()}));
vi.mock('../modules/auth/services/auth.api',()=>({login,me})); vi.mock('../services/http-client',()=>({httpClient:{post}}));
function Probe(){const auth=useAuth();return <><button onClick={()=>void auth.login('a@test.dev','secret').catch(()=>{})}>Login</button><button onClick={()=>auth.logout()}>Logout</button><p>{auth.user?.organization.name||'anonymous'}</p><p>{session.token||'no-token'}</p></>}; const renderProbe=()=>render(<QueryClientProvider client={new QueryClient()}><AuthProvider><Probe/></AuthProvider></QueryClientProvider>);
describe('AuthProvider',()=>{beforeEach(()=>{vi.clearAllMocks();session.set(null)});it('loads the session from auth me after login',async()=>{login.mockResolvedValue({accessToken:'token'});me.mockResolvedValue({id:'1',email:'a@test.dev',firstName:'Ana',lastName:'Pérez',organization:{id:'o',name:'Test Org'},roles:['AUDITOR'],permissions:['clients.read']});renderProbe();await userEvent.click(screen.getByText('Login'));expect(await screen.findByText('Test Org')).toBeInTheDocument();expect(session.token).toBe('token')});it('clears a partial session when auth me fails',async()=>{login.mockResolvedValue({accessToken:'token'});me.mockRejectedValue(new Error('unauthorized'));renderProbe();await userEvent.click(screen.getByText('Login'));expect(await screen.findByText('anonymous')).toBeInTheDocument();expect(session.token).toBeNull()});it('clears session on logout',async()=>{post.mockResolvedValue({});renderProbe();session.set('token');await userEvent.click(screen.getByText('Logout'));expect(session.token).toBeNull();expect(post).toHaveBeenCalledWith('/auth/logout')})});
