import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { render, screen, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router-dom';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { ClientsPage } from './clients-page';
import { clientsApi, type Client } from './services/clients.api';
vi.mock('../../app/use-auth',()=>({useAuth:()=>({hasPermission:()=>true})}));
afterEach(()=>vi.restoreAllMocks());
const renderPage=(url='/clientes')=>render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><MemoryRouter initialEntries={[url]}><ClientsPage/></MemoryRouter></QueryClientProvider>);
describe('Listado de clientes',()=>{
 it('muestra el estado vacío sin empresas inventadas',async()=>{vi.spyOn(clientsApi,'getClientPage').mockResolvedValue({items:[],total:0,page:1,pageSize:5});renderPage();expect(await screen.findByText('No hay clientes registrados.')).toBeInTheDocument();expect(screen.getByRole('link',{name:'Nuevo cliente'})).toHaveAttribute('href','/clientes/nuevo');expect(screen.queryByRole('columnheader',{name:'Estado'})).not.toBeInTheDocument()});
 it('muestra las 7 columnas definitivas y la acción Eliminar',async()=>{vi.spyOn(clientsApi,'getClientPage').mockResolvedValue({items:[{id:'c1',legalName:'Tía S.A.',taxId:'0012345678001',email:'empresa@example.test',representatives:[{treatment:'Sr.',fullName:'Juan Pérez',nationalId:'0012345678',position:'Gerente General'}]} as Client],total:1,page:1,pageSize:5});renderPage();expect(await screen.findByText('Tía S.A.')).toBeInTheDocument();const headers=screen.getAllByRole('columnheader').map(h=>h.textContent);expect(headers).toEqual(['#','Razón social','RUC','Representante legal','Cargo','Correo','Acciones']);expect(screen.queryByRole('columnheader',{name:'Teléfono'})).not.toBeInTheDocument();const row=screen.getByRole('row',{name:/Tía S\.A\./});expect(within(row).getByRole('link',{name:'Ver Tía S.A.'})).toHaveAttribute('href','/clientes/c1');expect(within(row).getByRole('link',{name:'Editar Tía S.A.'})).toHaveAttribute('href','/clientes/c1/editar');expect(within(row).getByRole('button',{name:'Eliminar Tía S.A.'})).toBeInTheDocument()});
 it('confirma, advierte contratos y permite cancelar sin llamar al backend',async()=>{const remove=vi.spyOn(clientsApi,'deleteClient');vi.spyOn(clientsApi,'getClientPage').mockResolvedValue({items:[{id:'c1',legalName:'Tía S.A.',taxId:'001',email:null,_count:{contracts:1}} as Client],total:1,page:1,pageSize:5});renderPage();await userEvent.click(await screen.findByRole('button',{name:'Eliminar Tía S.A.'}));expect(screen.getByRole('dialog')).toHaveTextContent('¿Está seguro de eliminar este cliente?');expect(screen.getByRole('dialog')).toHaveTextContent('contratos asociados');await userEvent.click(screen.getByRole('button',{name:'Cancelar'}));expect(remove).not.toHaveBeenCalled();expect(screen.queryByRole('dialog')).not.toBeInTheDocument()});
 it('elimina con el endpoint real y muestra confirmación',async()=>{vi.spyOn(clientsApi,'getClientPage').mockResolvedValue({items:[{id:'c1',legalName:'Tía S.A.',taxId:'001',email:null} as Client],total:1,page:1,pageSize:5});const remove=vi.spyOn(clientsApi,'deleteClient').mockResolvedValue({id:'c1',deletedAt:'2026-01-01T00:00:00.000Z',contractCount:0});renderPage();await userEvent.click(await screen.findByRole('button',{name:'Eliminar Tía S.A.'}));await userEvent.click(screen.getByRole('button',{name:'Eliminar cliente'}));expect(await screen.findByText('Cliente eliminado correctamente.')).toBeInTheDocument();expect(remove).toHaveBeenCalledWith('c1')});
 it('envía búsqueda y página al backend',async()=>{const get=vi.spyOn(clientsApi,'getClientPage').mockResolvedValue({items:[],total:12,page:2,pageSize:5});renderPage('/clientes?q=Representante&page=2');await screen.findByText('Mostrando 6 a 10 de 12 clientes');expect(get).toHaveBeenCalledWith(2,'Representante',expect.any(AbortSignal));await userEvent.click(screen.getByRole('button',{name:'Página siguiente'}));expect(get).toHaveBeenCalledWith(3,'Representante',expect.any(AbortSignal))});
 it('mantiene los errores de permisos visibles',async()=>{vi.spyOn(clientsApi,'getClientPage').mockRejectedValue({response:{status:403}});renderPage();expect(await screen.findByRole('alert')).toHaveTextContent('Acceso denegado');expect(screen.getByRole('button',{name:'Reintentar'})).toBeInTheDocument()});
});
