import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter, Routes, Route } from 'react-router-dom';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { ClientNewPage } from './client-new-page';
import { clientsApi, type Client } from './services/clients.api';
afterEach(()=>vi.restoreAllMocks());
const renderPage=()=>render(<QueryClientProvider client={new QueryClient()}><MemoryRouter initialEntries={['/clientes/nuevo']}><Routes><Route path="/clientes/nuevo" element={<ClientNewPage/>}/><Route path="/clientes" element={<p>Listado actualizado</p>}/></Routes></MemoryRouter></QueryClientProvider>);
describe('Registro de cliente',()=>{
 it('exige los 8 campos definitivos',async()=>{const create=vi.spyOn(clientsApi,'createClient');renderPage();await userEvent.click(screen.getByRole('button',{name:'Guardar cliente'}));expect(await screen.findByText('La razón social: campo obligatorio')).toBeInTheDocument();expect(screen.getByText('La actividad económica: campo obligatorio')).toBeInTheDocument();expect(screen.getByText('El correo de la empresa: campo obligatorio')).toBeInTheDocument();expect(screen.getByText('El representante: campo obligatorio')).toBeInTheDocument();expect(screen.getByText('La cédula: campo obligatorio')).toBeInTheDocument();expect(screen.getByText('El cargo: campo obligatorio')).toBeInTheDocument();expect(create).not.toHaveBeenCalled()});
 it('envía los 8 campos en una petición y vuelve al listado',async()=>{const create=vi.spyOn(clientsApi,'createClient').mockResolvedValue({id:'c1'} as Client);renderPage();for(const [label,value]of [['Razón social','Tía S.A.'],['RUC','0012345678001'],['Actividad económica principal','Venta al por menor de productos'],['Correo electrónico de la empresa','empresa@example.test'],['Nombre completo','Juan Carlos Pérez López'],['Cédula','0012345678'],['Cargo','Gerente General']])await userEvent.type(screen.getByLabelText(new RegExp(label)),value);await userEvent.selectOptions(screen.getByLabelText(/Tratamiento/),'Sra.');await userEvent.click(screen.getByRole('button',{name:'Guardar cliente'}));expect(await screen.findByText('Listado actualizado')).toBeInTheDocument();expect(create).toHaveBeenCalledWith(expect.objectContaining({country:'EC',legalName:'Tía S.A.',taxId:'0012345678001',economicActivity:'Venta al por menor de productos',email:'empresa@example.test',representative:expect.objectContaining({treatment:'Sra.',fullName:'Juan Carlos Pérez López',nationalId:'0012345678',position:'Gerente General'})}));expect(create.mock.calls[0][0]).not.toHaveProperty('phone');expect(create.mock.calls[0][0]).not.toHaveProperty('address')});
 it('rechaza correo de empresa inválido y tratamiento fuera de lista',async()=>{const create=vi.spyOn(clientsApi,'createClient');renderPage();await userEvent.type(screen.getByLabelText(/Correo electrónico de la empresa/),'incorrecto');await userEvent.click(screen.getByRole('button',{name:'Guardar cliente'}));expect(await screen.findByText('Ingrese un correo válido')).toBeInTheDocument();expect(create).not.toHaveBeenCalled()});
});
